// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkHere.Services.Database;

#nullable disable

namespace ParkHere.Services.Migrations
{
    [DbContext(typeof(ParkHereDbContext))]
    [Migration("20251225194041_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParkHere.Services.Database.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sarajevo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Banja Luka"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tuzla"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Zenica"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mostar"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bijeljina"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Prijedor"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Brčko"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Doboj"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Zvornik"
                        });
                });

            modelBuilder.Entity("ParkHere.Services.Database.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Female"
                        });
                });

            modelBuilder.Entity("ParkHere.Services.Database.ParkingReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("ParkingSpotId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParkingSpotId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("ParkingReservations");
                });

            modelBuilder.Entity("ParkHere.Services.Database.ParkingSector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ParkingSectors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FloorNumber = 0,
                            IsActive = true,
                            Name = "A1"
                        },
                        new
                        {
                            Id = 2,
                            FloorNumber = 1,
                            IsActive = true,
                            Name = "A2"
                        },
                        new
                        {
                            Id = 3,
                            FloorNumber = 2,
                            IsActive = true,
                            Name = "A3"
                        },
                        new
                        {
                            Id = 4,
                            FloorNumber = 3,
                            IsActive = false,
                            Name = "A4"
                        });
                });

            modelBuilder.Entity("ParkHere.Services.Database.ParkingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ActualStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExtraCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ExtraMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ParkingReservationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParkingReservationId");

                    b.ToTable("ParkingSessions");
                });

            modelBuilder.Entity("ParkHere.Services.Database.ParkingSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<int>("ParkingSpotTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ParkingWingId")
                        .HasColumnType("int");

                    b.Property<string>("SpotCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ParkingSpotTypeId");

                    b.HasIndex("ParkingWingId");

                    b.ToTable("ParkingSpots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            IsOccupied = false,
                            ParkingSpotTypeId = 1,
                            ParkingWingId = 1,
                            SpotCode = "A1-  L1"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            IsOccupied = false,
                            ParkingSpotTypeId = 1,
                            ParkingWingId = 2,
                            SpotCode = "A1-  R1"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            IsOccupied = false,
                            ParkingSpotTypeId = 2,
                            ParkingWingId = 3,
                            SpotCode = "A2-  L1"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            IsOccupied = false,
                            ParkingSpotTypeId = 2,
                            ParkingWingId = 4,
                            SpotCode = "A2-  R1"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            IsOccupied = false,
                            ParkingSpotTypeId = 3,
                            ParkingWingId = 5,
                            SpotCode = "A3-  L1"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            IsOccupied = false,
                            ParkingSpotTypeId = 3,
                            ParkingWingId = 6,
                            SpotCode = "A3-  R1"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = false,
                            IsOccupied = false,
                            ParkingSpotTypeId = 1,
                            ParkingWingId = 7,
                            SpotCode = "A4-  L1"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = false,
                            IsOccupied = false,
                            ParkingSpotTypeId = 1,
                            ParkingWingId = 8,
                            SpotCode = "A4-  R1"
                        });
                });

            modelBuilder.Entity("ParkHere.Services.Database.ParkingSpotType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("PriceMultiplier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ParkingSpotTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            PriceMultiplier = 1.00m,
                            Type = "Regular"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            PriceMultiplier = 1.50m,
                            Type = "VIP"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            PriceMultiplier = 0.75m,
                            Type = "Handicapped"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            PriceMultiplier = 1.20m,
                            Type = "Electric"
                        });
                });

            modelBuilder.Entity("ParkHere.Services.Database.ParkingWing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParkingSectorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParkingSectorId");

                    b.ToTable("ParkingWings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Left",
                            ParkingSectorId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Right",
                            ParkingSectorId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Left",
                            ParkingSectorId = 2
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Right",
                            ParkingSectorId = 2
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Left",
                            ParkingSectorId = 3
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Right",
                            ParkingSectorId = 3
                        },
                        new
                        {
                            Id = 7,
                            IsActive = false,
                            Name = "Left",
                            ParkingSectorId = 4
                        },
                        new
                        {
                            Id = 8,
                            IsActive = false,
                            Name = "Right",
                            ParkingSectorId = 4
                        });
                });

            modelBuilder.Entity("ParkHere.Services.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full system access and administrative privileges",
                            IsActive = true,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Standard user with limited system access",
                            IsActive = true,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("ParkHere.Services.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GenderId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "adil.joldic@parkhere.com",
                            FirstName = "Adil",
                            GenderId = 1,
                            IsActive = true,
                            LastName = "Joldic",
                            PasswordHash = "SKCEf8PFXFpwXefUyKkpl6MMBen54WiyctXTCdWrHd0=",
                            PasswordSalt = "aGk9AqtPuyMxuMw5kVMi5A==",
                            PhoneNumber = "+387 61 123 456",
                            Username = "desktop"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "parkhere.receive@gmail.com",
                            FirstName = "Benjamin",
                            GenderId = 1,
                            IsActive = true,
                            LastName = "Cero",
                            PasswordHash = "+/pM4+5rgrwaezXoDcdKMtyc2Q7IM+rGT5qT8AOUBRE=",
                            PasswordSalt = "BPiZbadjt6lpsQKO4wB1aQ==",
                            PhoneNumber = "+387 61 123 456",
                            Username = "user"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "elmir.babovic@parkhere.com",
                            FirstName = "Elmir",
                            GenderId = 1,
                            IsActive = true,
                            LastName = "Babovic",
                            PasswordHash = "vlAx8k6vnwwlvR7VmvHyN82cIDhXROKGCAoEKA7BwFI=",
                            PasswordSalt = "HBQrLQGqNOmja95IBkWlfw==",
                            PhoneNumber = "+387 61 123 456",
                            Username = "admin2"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "haris.horozovic@example.com",
                            FirstName = "Haris",
                            GenderId = 1,
                            IsActive = true,
                            LastName = "Horozovic",
                            PasswordHash = "5H4NYDgDMf/fY9PDV8qW9Wz29pk05xBZ0FF4A9/Lisw=",
                            PasswordSalt = "kqXcBL1vn7jyn4Bm/tilwQ==",
                            PhoneNumber = "+387 61 123 456",
                            Username = "user4"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "faris.festic@example.com",
                            FirstName = "Faris",
                            GenderId = 2,
                            IsActive = true,
                            LastName = "Festic",
                            PasswordHash = "5H4NYDgDMf/fY9PDV8qW9Wz29pk05xBZ0FF4A9/Lisw=",
                            PasswordSalt = "kqXcBL1vn7jyn4Bm/tilwQ==",
                            PhoneNumber = "+387 61 123 456",
                            Username = "user5"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "adna.adnic@example.com",
                            FirstName = "Adna",
                            GenderId = 1,
                            IsActive = true,
                            LastName = "Adnic",
                            PasswordHash = "5H4NYDgDMf/fY9PDV8qW9Wz29pk05xBZ0FF4A9/Lisw=",
                            PasswordSalt = "kqXcBL1vn7jyn4Bm/tilwQ==",
                            PhoneNumber = "+387 61 123 456",
                            Username = "user6"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "edin.edinic@example.com",
                            FirstName = "Edin",
                            GenderId = 2,
                            IsActive = true,
                            LastName = "Edinic",
                            PasswordHash = "5H4NYDgDMf/fY9PDV8qW9Wz29pk05xBZ0FF4A9/Lisw=",
                            PasswordSalt = "kqXcBL1vn7jyn4Bm/tilwQ==",
                            PhoneNumber = "+387 61 123 456",
                            Username = "user7"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maja.majic@example.com",
                            FirstName = "Maja",
                            GenderId = 1,
                            IsActive = true,
                            LastName = "Majic",
                            PasswordHash = "5H4NYDgDMf/fY9PDV8qW9Wz29pk05xBZ0FF4A9/Lisw=",
                            PasswordSalt = "kqXcBL1vn7jyn4Bm/tilwQ==",
                            PhoneNumber = "+387 61 123 456",
                            Username = "user8"
                        },
                        new
                        {
                            Id = 9,
                            CityId = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sara.saric@example.com",
                            FirstName = "Sara",
                            GenderId = 2,
                            IsActive = true,
                            LastName = "Saric",
                            PasswordHash = "5H4NYDgDMf/fY9PDV8qW9Wz29pk05xBZ0FF4A9/Lisw=",
                            PasswordSalt = "kqXcBL1vn7jyn4Bm/tilwQ==",
                            PhoneNumber = "+387 61 123 456",
                            Username = "user9"
                        },
                        new
                        {
                            Id = 10,
                            CityId = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ivan.ivic@example.com",
                            FirstName = "Ivan",
                            GenderId = 1,
                            IsActive = true,
                            LastName = "Ivic",
                            PasswordHash = "5H4NYDgDMf/fY9PDV8qW9Wz29pk05xBZ0FF4A9/Lisw=",
                            PasswordSalt = "kqXcBL1vn7jyn4Bm/tilwQ==",
                            PhoneNumber = "+387 61 123 456",
                            Username = "user10"
                        },
                        new
                        {
                            Id = 11,
                            CityId = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "luka.lukic@example.com",
                            FirstName = "Luka",
                            GenderId = 2,
                            IsActive = true,
                            LastName = "Lukic",
                            PasswordHash = "5H4NYDgDMf/fY9PDV8qW9Wz29pk05xBZ0FF4A9/Lisw=",
                            PasswordSalt = "kqXcBL1vn7jyn4Bm/tilwQ==",
                            PhoneNumber = "+387 61 123 456",
                            Username = "user11"
                        },
                        new
                        {
                            Id = 12,
                            CityId = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ana.anic@example.com",
                            FirstName = "Ana",
                            GenderId = 1,
                            IsActive = true,
                            LastName = "Anic",
                            PasswordHash = "5H4NYDgDMf/fY9PDV8qW9Wz29pk05xBZ0FF4A9/Lisw=",
                            PasswordSalt = "kqXcBL1vn7jyn4Bm/tilwQ==",
                            PhoneNumber = "+387 61 123 456",
                            Username = "user12"
                        });
                });

            modelBuilder.Entity("ParkHere.Services.Database.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAssigned = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateAssigned = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateAssigned = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            DateAssigned = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            DateAssigned = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            DateAssigned = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            DateAssigned = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            DateAssigned = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            DateAssigned = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            DateAssigned = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            DateAssigned = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            DateAssigned = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 12
                        });
                });

            modelBuilder.Entity("ParkHere.Services.Database.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            LicensePlate = "ABC-123",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            LicensePlate = "DEF-456",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            LicensePlate = "GHI-789",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            LicensePlate = "JKL-012",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("ParkHere.Services.Database.ParkingReservation", b =>
                {
                    b.HasOne("ParkHere.Services.Database.ParkingSpot", "ParkingSpot")
                        .WithMany()
                        .HasForeignKey("ParkingSpotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkHere.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkHere.Services.Database.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParkingSpot");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ParkHere.Services.Database.ParkingSession", b =>
                {
                    b.HasOne("ParkHere.Services.Database.ParkingReservation", "ParkingReservation")
                        .WithMany()
                        .HasForeignKey("ParkingReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParkingReservation");
                });

            modelBuilder.Entity("ParkHere.Services.Database.ParkingSpot", b =>
                {
                    b.HasOne("ParkHere.Services.Database.ParkingSpotType", "ParkingSpotType")
                        .WithMany()
                        .HasForeignKey("ParkingSpotTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParkHere.Services.Database.ParkingWing", "ParkingWing")
                        .WithMany()
                        .HasForeignKey("ParkingWingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParkingSpotType");

                    b.Navigation("ParkingWing");
                });

            modelBuilder.Entity("ParkHere.Services.Database.ParkingWing", b =>
                {
                    b.HasOne("ParkHere.Services.Database.ParkingSector", "ParkingSector")
                        .WithMany()
                        .HasForeignKey("ParkingSectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParkingSector");
                });

            modelBuilder.Entity("ParkHere.Services.Database.User", b =>
                {
                    b.HasOne("ParkHere.Services.Database.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ParkHere.Services.Database.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("ParkHere.Services.Database.UserRole", b =>
                {
                    b.HasOne("ParkHere.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParkHere.Services.Database.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ParkHere.Services.Database.Vehicle", b =>
                {
                    b.HasOne("ParkHere.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ParkHere.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ParkHere.Services.Database.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
